import SectionHeading from './SectionHeading';
import SectionReveal from './SectionReveal';
import { serviceHighlights } from './home-data';

export default function ServiceHighlightsSection() {
  return (
    <section className="container py-10">
      <SectionReveal>
        <div className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr]">
          <div className="surface-panel rounded-[32px] p-6 md:p-8">
            <SectionHeading
              eyebrow="Service design"
              title="Shopping support that feels more like a studio concierge"
              copy="Adding another section here helps balance the product rails and keeps the homepage feeling complete."
            />
            <div className="mt-8 grid gap-4 sm:grid-cols-2">
              {serviceHighlights.map(({ title, text, icon: Icon }) => (
                <div key={title} className="rounded-[26px] border border-stone-200 bg-white p-5">
                  <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-mist text-primary">
                    <Icon size={20} />
                  </div>
                  <h3 className="mt-4 text-lg font-semibold text-stone-900">{title}</h3>
                  <p className="mt-2 text-sm leading-6 text-stone-600">{text}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="grid gap-6">
            <div className="relative overflow-hidden rounded-[32px]">
              <div className="aspect-[4/3.1]">
                <img
                  src="https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80"
                  alt="Curated fashion details"
                  className="h-full w-full object-cover"
                />
              </div>
              <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent" />
              <div className="absolute bottom-0 left-0 right-0 p-6">
                <p className="text-[11px] font-semibold uppercase tracking-[0.3em] text-white/60">Styled with intent</p>
                <h3 className="mt-3 text-3xl font-semibold text-white">A homepage that feels merchandised, not autogenerated</h3>
              </div>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="surface-panel rounded-[28px] p-5">
                <p className="text-3xl font-extrabold text-stone-900">2.4M+</p>
                <p className="mt-2 text-[11px] font-semibold uppercase tracking-[0.28em] text-stone-500">Returning customers</p>
              </div>
              <div className="surface-panel rounded-[28px] p-5">
                <p className="text-3xl font-extrabold text-stone-900">98.5%</p>
                <p className="mt-2 text-[11px] font-semibold uppercase tracking-[0.28em] text-stone-500">Satisfaction score</p>
              </div>
            </div>
          </div>
        </div>
      </SectionReveal>
    </section>
  );
}
